"""
Robust Batch Processor for "日本帝國港灣統計"
Supports incremental saving and resuming.
"""

import os
import hybrid_extractor
import concurrent.futures
import time
import glob

def process_and_save_page(page_info):
    """
    Process one page and save immediately to Markdown file.
    """
    page_num, image_path, output_dir = page_info
    md_filename = os.path.join(output_dir, f"page_{page_num:03d}.md")
    
    # Check simple existence for resume
    if os.path.exists(md_filename):
        # Also check if non-empty
        if os.path.getsize(md_filename) > 10:
            return page_num, "Skipped", 0

    try:
        start_time = time.time()
        
        if 1 <= page_num <= 6:
            # Text Mode
            content = hybrid_extractor.extract_vertical_text(image_path)
            # Wrap in minimal markdown
            result = f"\n\n## Page {page_num}\n\n{content}\n"
            
        else:
            # Table Mode
            rows = hybrid_extractor.extract_table_content(image_path)
            if not rows:
                result = f"\n\n## Page {page_num}\n\n(No table data detected)\n"
            else:
                lines = []
                lines.append(f"\n\n## Page {page_num}")
                # Construct Markdown Table
                for row_idx, row in enumerate(rows):
                    # Clean up: Replace pipes with generic separator or escape them
                    clean_row = [str(c).replace('|', '') for c in row if c is not None]
                    lines.append("| " + " | ".join(clean_row) + " |")
                result = "\n".join(lines)
        
        # Save immediately
        if not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)
            
        with open(md_filename, 'w', encoding='utf-8') as f:
            f.write(result)
            
        elapsed = time.time() - start_time
        return page_num, "Processed", elapsed
        
    except Exception as e:
        error_msg = f"\n## Page {page_num}\nError: {str(e)}\n"
        with open(md_filename, 'w', encoding='utf-8') as f:
            f.write(error_msg)
        return page_num, f"Error: {str(e)}", 0

def combine_results(intermediate_dir, final_output_file):
    """
    Combine all page_XXX.md files into one.
    """
    # Glob returns string paths
    files = glob.glob(os.path.join(intermediate_dir, "page_*.md"))
    # Sort files naturally
    files.sort()
    
    with open(final_output_file, 'w', encoding='utf-8') as outfile:
        outfile.write("# 日本帝國港灣統計 OCR Result\n\nGenerated by Hybrid Structure-Aware OCR (Robust Batch)\n\n")
        
        for md_file in files:
            with open(md_file, 'r', encoding='utf-8') as infile:
                content = infile.read()
                outfile.write(content)
                outfile.write("\n\n---\n\n")
    
    print(f"Combined {len(files)} pages into {final_output_file}")

if __name__ == "__main__":
    pages_dir = r"c:\Users\User\Downloads\日本帝國港灣統計_0001\pages_gamma_strong"
    intermediate_dir = r"c:\Users\User\Downloads\日本帝國港灣統計_0001\intermediate_md_strong"
    final_output_file = r"c:\Users\User\Downloads\日本帝國港灣統計_0001\Full_Output_Strong.md"
    
    if not os.path.exists(intermediate_dir):
        os.makedirs(intermediate_dir)
    
    # Get all page files
    files = sorted([f for f in os.listdir(pages_dir) if f.lower().endswith('.png')])
    
    # Map filenames to page numbers (assuming page_XXX.png)
    page_tasks = []
    
    for f in files:
        # Filter out debug images
        if f.startswith('debug_') or f.startswith('table_') or 'debug' in f:
            continue
            
        try:
            num_str = f.split('_')[-1].split('.')[0]
            num = int(num_str)
            page_tasks.append((num, os.path.join(pages_dir, f), intermediate_dir))
        except:
            continue
            
    # Sort by page number
    page_tasks.sort(key=lambda x: x[0])
    
    print(f"Starting robust batch processing for {len(page_tasks)} pages...")
    
    max_workers = 4 
    
    count = 0 
    total = len(page_tasks)
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(process_and_save_page, task): task for task in page_tasks}
        
        for future in concurrent.futures.as_completed(futures):
            try:
                p_num, status, dur = future.result()
                count += 1
                if status == "Skipped":
                    # Don't spam unless needed, or just print progress
                    if count % 10 == 0:
                        print(f"[{count}/{total}] Skipped existing pages...")
                else:
                    print(f"[{count}/{total}] Page {p_num} {status} in {dur:.2f}s")
            except Exception as e:
                print(f"Worker failed: {e}")

    print("Processing complete. Combining results...")
    combine_results(intermediate_dir, final_output_file)
